### PR TITLE
Implement __str__ to improve readability (it includes TQ42-1437, TQ42-1445, TQ42-1447) 

### PR DESCRIPTION
**Pull request by lusnig**

### CODE REVIEW

**Comment by rbattq** [comment]
@lusnig please give a better description of this PR.

Why only add `__str__` to one class? There are many that need exactly this same modification.

**Review by sbtq — CHANGES_REQUESTED** [review]
Agree with @rbattq on that point, please give a better title and description to this PR.
What are you trying to improve? Ticket number?

If you are doing it like this for `ExperimentRun`, why not do it for the others as well?

**Comment by lusnig** [comment]
When we return the status of the run or the list of the projects, organisations and experiments the output is not human readable so I would to propose to implement the under method `__str__` for allowing to print out all the interesting information in an human readable format.

In the following comments I ll insert the tickets descriptions

**Comment by lusnig** [comment]
[tq42-1437 Display user friendly strings for experiment run status checks](https://terraquantum.atlassian.net/browse/TQ42-1437):

Experiment run statuses returned by run.check() and run.poll() are currently raw protobuf objects which do not display as sensible strings that users can understand. It would be better if these two functions returned a wrapper object of some sort which contained the protobuf object and had a __str__ method to display useful information about the experiment run.

**Comment by lusnig** [comment]
Add the same functionality to  classes `Compute`  and `Dataset`  just to make it consistent

**Review by sbtq — CHANGES_REQUESTED** [review]
Bump the version in the pyproject.toml so merging these changes actually work.

**Review by sbtq — APPROVED** [review]

**Pull request merged**
